CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "phone" varchar,
  "profile_photo_url" varchar,
  "user_type" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "user_settings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "notifications_enabled" boolean,
  "privacy_level" varchar,
  "language" varchar,
  "timezone" varchar
);

CREATE TABLE "user_address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "country" varchar,
  "city" varchar,
  "address" varchar,
  "lat" float,
  "lng" float
);

CREATE TABLE "pets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" int,
  "name" varchar,
  "species" varchar,
  "breed" varchar,
  "sex" varchar,
  "birthdate" date,
  "weight" float,
  "avatar_url" varchar,
  "created_at" timestamp
);

CREATE TABLE "pet_vaccines" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "vaccine_name" varchar,
  "date" date,
  "next_due" date,
  "vet_clinic" varchar,
  "notes" varchar
);

CREATE TABLE "pet_medications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "medication" varchar,
  "dose" varchar,
  "frequency" varchar,
  "start_date" date,
  "end_date" date,
  "notes" varchar
);

CREATE TABLE "pet_weight_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "date" date,
  "weight" float
);

CREATE TABLE "pet_media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "url" varchar,
  "media_type" varchar
);

CREATE TABLE "pet_medical_visits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "vet_id" int,
  "visit_date" date,
  "diagnosis" varchar,
  "treatment" varchar,
  "notes" varchar
);

CREATE TABLE "pet_vaccine_card_scans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "file_url" varchar,
  "extracted_text" text,
  "ocr_metadata" text
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "pet_id" int,
  "content" text,
  "media_urls" text,
  "visibility" varchar,
  "created_at" timestamp
);

CREATE TABLE "post_likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "user_id" int
);

CREATE TABLE "post_comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "user_id" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "photo_url" varchar,
  "type" varchar
);

CREATE TABLE "group_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int,
  "user_id" int,
  "role" varchar
);

CREATE TABLE "friendships" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_1" int,
  "user_2" int,
  "status" varchar
);

CREATE TABLE "chats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_group" boolean
);

CREATE TABLE "chat_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int,
  "user_id" int
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int,
  "sender_id" int,
  "text" text,
  "media_url" varchar,
  "created_at" timestamp
);

CREATE TABLE "places" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "description" varchar,
  "lat" float,
  "lng" float,
  "phone" varchar,
  "website" varchar,
  "services" text,
  "created_by_user" int
);

CREATE TABLE "place_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" int,
  "user_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "place_reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" int,
  "user_id" int,
  "report_type" varchar,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "vet_clinics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" int,
  "name" varchar,
  "description" varchar,
  "address" varchar,
  "lat" float,
  "lng" float,
  "phone" varchar,
  "email" varchar,
  "logo_url" varchar
);

CREATE TABLE "vet_services" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "clinic_id" int,
  "service_name" varchar,
  "price" float,
  "description" varchar
);

CREATE TABLE "appointments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "clinic_id" int,
  "pet_id" int,
  "user_id" int,
  "vet_id" int,
  "date" date,
  "time" varchar,
  "status" varchar
);

CREATE TABLE "shop_products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "name" varchar,
  "description" varchar,
  "price" float,
  "stock" int,
  "image_url" varchar
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "user_id" int,
  "total" float,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "price" float
);

CREATE TABLE "ai_recommendations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "recommendation_type" varchar,
  "content" text,
  "metadata" text,
  "created_at" timestamp
);

CREATE TABLE "ai_chat_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "pet_id" int,
  "prompt" text,
  "response" text,
  "created_at" timestamp
);

CREATE TABLE "embeddings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entity_type" varchar,
  "entity_id" int,
  "vector" text,
  "metadata" text
);

ALTER TABLE "user_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_address" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "pets" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "pet_vaccines" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "pet_medications" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "pet_weight_history" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "pet_media" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "pet_medical_visits" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "pet_medical_visits" ADD FOREIGN KEY ("vet_id") REFERENCES "users" ("id");

ALTER TABLE "pet_vaccine_card_scans" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "post_likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "post_comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "group_members" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "group_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_1") REFERENCES "users" ("id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_2") REFERENCES "users" ("id");

ALTER TABLE "chat_members" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "chat_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "places" ADD FOREIGN KEY ("created_by_user") REFERENCES "users" ("id");

ALTER TABLE "place_reviews" ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");

ALTER TABLE "place_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "place_reports" ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");

ALTER TABLE "place_reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "vet_clinics" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "vet_services" ADD FOREIGN KEY ("clinic_id") REFERENCES "vet_clinics" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("clinic_id") REFERENCES "vet_clinics" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("vet_id") REFERENCES "users" ("id");

ALTER TABLE "shop_products" ADD FOREIGN KEY ("shop_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("shop_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "shop_products" ("id");

ALTER TABLE "ai_recommendations" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");

ALTER TABLE "ai_chat_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "ai_chat_history" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("id");
